language: python
python:
  - "2.7"
install:
  - pip install pep8==1.5.7 --use-mirrors
  - pip install coveralls
before_script:
  - cd vaas-app
  - "pep8 --first --show-source --show-pep8 src/"
script:
  - coverage run --rcfile=src/.coveragerc --source vaas ./setup.py test
after_success:
  - coveralls
