language: python
python:
  - "3.5"
install:
  - pip install --upgrade pip setuptools
  - pip install pep8==1.5.7
  - pip install coveralls
before_script:
  - cd vaas-app
  - "pep8 --first --show-source --show-pep8 src/"
script:
  - coverage run --rcfile=src/.coveragerc --source vaas ./setup.py test
after_success:
  - coveralls
