version: "3.9"
services:
  uwsgi:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3030:3030
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 3s
  celery-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
  celery-cron-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
  celery-routes-test:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
  celery-scheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
