site_name: VaaS
pages:
- ['index.md', 'About']
- ['quick-start/vagrant.md', 'Quick Start', 'VaaS in Vagrant']
- ['quick-start/docker.md', 'Quick Start', 'VaaS in Docker']
- ['quick-start/production.md', 'Quick Start', 'VaaS in Production']
- ['documentation/gui.md', 'Documentation', 'VaaS GUI']
- ['documentation/api.md', 'Documentation', 'VaaS API']
- ['documentation/vcl.md', 'Documentation', 'VCL templates']
- ['documentation/dc.md', 'Documentation', 'VaaS in multiple DC scenario']
- ['documentation/ldap.md', 'Documentation', 'Authentication with LDAP']
- ['documentation/cron.md', 'Documentation', 'VaaS cron jobs']
