---
DEBUG: False
TEMPLATE_DEBUG: False
STATIC_ROOT: /home/ubuntu/static
ALLOWED_HOSTS:
 - '*'
AUTHENTICATION_BACKENDS:
  - django.contrib.auth.backends.ModelBackend
default:
  ENGINE: 'django.db.backends.sqlite3'
  NAME: /tmp/db.sqlite3
