name: Django CI/CD Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip coverage
        pip install -r ./vaas-app/requirements/test.txt
    - name: Lint with pep8
      working-directory: vaas-app
      run: |
        pep8 --first --show-source --show-pep8 src/
    - name: Test with coverage
      working-directory: vaas-app
      run: |
        coverage run --rcfile=src/.coveragerc --source vaas ./setup.py test
