name: VaaS Deployment Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.5
      MYSQL_VERSION: 1.4.2.post1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system packages
        run: |
          sudo apt-get install python3.5-dev python3-venv libssl-dev libtool libldap2-dev libssl-dev libsasl2-dev libmysqlclient-dev libcurl4-openssl-dev
      - name: Build VaaS package
        run: |
          git clone https://github.com/allegro/vaas.git
          python3.5 -m venv dist-env
          . dist-env/bin/activate
          pip install --upgrade pip
          cd vaas/vaas-app
          python setup.py egg_info
          pip install -r src/vaas.egg-info/requires.txt
          python setup.py sdist --format=zip
      - name: Install VaaS dependencies
        run: |
          python3.5 -m venv prod-env
          . prod-env/bin/activate
          pip install --upgrade pip
          pip install python-ldap==3.2.0
          pip install django-auth-ldap==1.7.0
          pip install mysqlclient==1.4.2.post1
          pip install lck.django
          pip install uwsgi
          pip install vaas-{version-number}.zip
      - name: Configure Uwsgi
        run: |
          sudo cp /path/to/uwsgi.conf /etc/init/uwsgi.conf
          sudo service uwsgi start
      - name: Configure Nginx
        run: |
          sudo ln -s /etc/nginx/sites-available/vaas.conf /etc/nginx/sites-enabled/vaas.conf
          sudo service nginx start
      - name: Troubleshooting
        run: |
          export LC_ALL="en_US.UTF-8"
          export LC_CTYPE="en_US.UTF-8"
          sudo dpkg-reconfigure locales

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION:\s*3.5
      MYSQL_VERSION: 1.4.2.post1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system packages
        run: |
          sudo apt-get install python3.5-dev python3-venv libssl-dev libtool libldap2-dev libssl-dev libsasl2-dev libmysqlclient-dev libcurl4-openssl-dev

      - name: Build VaaS package
        run: |
          git clone https://github.com/allegro/vaas.git
          python3.5 -m venv dist-env
          . dist-env/bin/activate
          pip install --upgrade pip
          cd vaas/vaas-app
          python setup.py egg_info
          pip install -r src/vaas.egg-info/requires.txt
          python setup.py sdist --format=zip
        run: |
          git clone https://github.com/allegro/vaas.git
          python3.5 -m venv dist-env
          . dist-env/bin/activate
          pip install --upgrade pip
          cd vaas/vaas-app
          python setup.py egg_info
          pip install -r src/vaas.egg-info/requires.txt
          python setup.py sdist --format=zip

      - name: Install VaaS package
        run: |
          python3.5 -m venv prod-env
          . prod-env/bin/activate
          pip install --upgrade pip
          pip install python-ldap==3.2.0
          pip install django-auth-ldap==1.7.0
          pip install mysqlclient==1.4.2.post1
          pip install lck.django
          pip install uwsgi
          pip install vaas-{version-number}.zip
          pip install --upgrade pip
          pip install python-ldap==3.2.0
          pip install django-auth-ldap==1.7.0
          pip install mysqlclient==1.4.2.post1
          pip install lck.django
          pip install uwsgi
          pip install vaas-{version-number}.zip
          pip install python-ldap==3.2.0
          pip install django-auth-ldap==1.7.0
          pip install mysqlclient==1.4.2.post1
          pip install lck.django
          pip install uwsgi
          pip install vaas-{version-number}.zip
          pip install --upgrade pip
          pip install python-ldap==3.2.0
          pip install django-auth-ldap==1.7.0
          pip install mysqlclient==1.4.2.post1
          pip install lck.django
          pip install uwsgi
          pip install vaas-{version-number}.zip

      - name: Configure Uwsgi
        run: |
          sudo cp /path/to/uwsgi.conf /etc/init/uwsgi.conf
          sudo service uwsgi start
        run: |
          sudo cp /path/to/uwsgi.conf /etc/init/uwsgi.conf
          sudo service uwsgi start

      - name: Configure Nginx
        run: |
          sudo ln -s /etc/nginx/sites-available/vaas.conf /etc/nginx/sites-enabled/vaas.conf
          sudo service nginx start

      - name: Troubleshooting
        run: |
          export LC_ALL="en_US.UTF-8"
          export LC_CTYPE="en_US.UTF-8"
          sudo dpkg-reconfigure locales
        run: |
          export LC_ALL="en_US.UTF-8"
          export LC_CTYPE="en_US.UTF-8"
          sudo dpkg-reconfigure locales
